df=read.csv("C:/Users/use/Documents/new_R/new_R/assgn1_explore.csv")
df$dt=strptime(paste(df$Date,df$Time,sep=" "),"%d-%m-%y %H:%M:%S")
png("plot3.png", width=480, height=480)
plot(df$dt, df$Sub_metering_1, type="l", xlab="", ylab="Energy Submetering")
lines(df$dt, df$Sub_metering_2, type="l", col="red")
lines(df$dt, df$Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), cex=0.75,lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.off()